#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -std=c++11 -Wall
RESINC = 
LIBDIR = 
LIB = -lboost_program_options -lboost_thread -lboost_system -lpthread
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g -D_DEBUG
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/sapcd

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/sapcd

OBJ_DEBUG = $(OBJDIR_DEBUG)/pystring_extend/data_conv.o $(OBJDIR_DEBUG)/pystring_extend/pystring_utf32_function.o $(OBJDIR_DEBUG)/pystring_extend/pystring_function.o $(OBJDIR_DEBUG)/pystring_extend/pystring_class.o $(OBJDIR_DEBUG)/pystring_extend/ConvertUTF.o $(OBJDIR_DEBUG)/proc_limit.o $(OBJDIR_DEBUG)/main.o $(OBJDIR_DEBUG)/ip_list_filter.o $(OBJDIR_DEBUG)/data_size_list_filter.o $(OBJDIR_DEBUG)/async_smtp_scanner.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/pystring_extend/data_conv.o $(OBJDIR_RELEASE)/pystring_extend/pystring_utf32_function.o $(OBJDIR_RELEASE)/pystring_extend/pystring_function.o $(OBJDIR_RELEASE)/pystring_extend/pystring_class.o $(OBJDIR_RELEASE)/pystring_extend/ConvertUTF.o $(OBJDIR_RELEASE)/proc_limit.o $(OBJDIR_RELEASE)/main.o $(OBJDIR_RELEASE)/ip_list_filter.o $(OBJDIR_RELEASE)/data_size_list_filter.o $(OBJDIR_RELEASE)/async_smtp_scanner.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/pystring_extend || mkdir -p $(OBJDIR_DEBUG)/pystring_extend
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/pystring_extend/data_conv.o: pystring_extend/data_conv.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c pystring_extend/data_conv.cpp -o $(OBJDIR_DEBUG)/pystring_extend/data_conv.o

$(OBJDIR_DEBUG)/pystring_extend/pystring_utf32_function.o: pystring_extend/pystring_utf32_function.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c pystring_extend/pystring_utf32_function.cpp -o $(OBJDIR_DEBUG)/pystring_extend/pystring_utf32_function.o

$(OBJDIR_DEBUG)/pystring_extend/pystring_function.o: pystring_extend/pystring_function.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c pystring_extend/pystring_function.cpp -o $(OBJDIR_DEBUG)/pystring_extend/pystring_function.o

$(OBJDIR_DEBUG)/pystring_extend/pystring_class.o: pystring_extend/pystring_class.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c pystring_extend/pystring_class.cpp -o $(OBJDIR_DEBUG)/pystring_extend/pystring_class.o

$(OBJDIR_DEBUG)/pystring_extend/ConvertUTF.o: pystring_extend/ConvertUTF.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c pystring_extend/ConvertUTF.c -o $(OBJDIR_DEBUG)/pystring_extend/ConvertUTF.o

$(OBJDIR_DEBUG)/proc_limit.o: proc_limit.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c proc_limit.cpp -o $(OBJDIR_DEBUG)/proc_limit.o

$(OBJDIR_DEBUG)/main.o: main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.cpp -o $(OBJDIR_DEBUG)/main.o

$(OBJDIR_DEBUG)/ip_list_filter.o: ip_list_filter.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ip_list_filter.cpp -o $(OBJDIR_DEBUG)/ip_list_filter.o

$(OBJDIR_DEBUG)/data_size_list_filter.o: data_size_list_filter.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c data_size_list_filter.cpp -o $(OBJDIR_DEBUG)/data_size_list_filter.o

$(OBJDIR_DEBUG)/async_smtp_scanner.o: async_smtp_scanner.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c async_smtp_scanner.cpp -o $(OBJDIR_DEBUG)/async_smtp_scanner.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/pystring_extend
	rm -rf $(OBJDIR_DEBUG)

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/pystring_extend || mkdir -p $(OBJDIR_RELEASE)/pystring_extend
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/pystring_extend/data_conv.o: pystring_extend/data_conv.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c pystring_extend/data_conv.cpp -o $(OBJDIR_RELEASE)/pystring_extend/data_conv.o

$(OBJDIR_RELEASE)/pystring_extend/pystring_utf32_function.o: pystring_extend/pystring_utf32_function.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c pystring_extend/pystring_utf32_function.cpp -o $(OBJDIR_RELEASE)/pystring_extend/pystring_utf32_function.o

$(OBJDIR_RELEASE)/pystring_extend/pystring_function.o: pystring_extend/pystring_function.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c pystring_extend/pystring_function.cpp -o $(OBJDIR_RELEASE)/pystring_extend/pystring_function.o

$(OBJDIR_RELEASE)/pystring_extend/pystring_class.o: pystring_extend/pystring_class.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c pystring_extend/pystring_class.cpp -o $(OBJDIR_RELEASE)/pystring_extend/pystring_class.o

$(OBJDIR_RELEASE)/pystring_extend/ConvertUTF.o: pystring_extend/ConvertUTF.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c pystring_extend/ConvertUTF.c -o $(OBJDIR_RELEASE)/pystring_extend/ConvertUTF.o

$(OBJDIR_RELEASE)/proc_limit.o: proc_limit.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c proc_limit.cpp -o $(OBJDIR_RELEASE)/proc_limit.o

$(OBJDIR_RELEASE)/main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)/main.o

$(OBJDIR_RELEASE)/ip_list_filter.o: ip_list_filter.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ip_list_filter.cpp -o $(OBJDIR_RELEASE)/ip_list_filter.o

$(OBJDIR_RELEASE)/data_size_list_filter.o: data_size_list_filter.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c data_size_list_filter.cpp -o $(OBJDIR_RELEASE)/data_size_list_filter.o

$(OBJDIR_RELEASE)/async_smtp_scanner.o: async_smtp_scanner.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c async_smtp_scanner.cpp -o $(OBJDIR_RELEASE)/async_smtp_scanner.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/pystring_extend
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

